name: 'enovitae-bot'
description: 'The bot automating the enovitae organization publications'
author: 'enovitae'

branding:
  icon: 'activity'
  color: 'red'

inputs:
  github_token:
    description: 'GITHUB_TOKEN'
    required: false
    default: '${{ github.token }}'
  username:
    description: The username of the bot
    required: false
    default: bot
  code_path:
    description: Path of project's code
    required: false
  content_path:
    description: Path of project's content mdx files
    required: false
  db_file:
    description: DB file
    required: false

runs:
  using: node20
  main: dist/index.js
