name: 'enovitae-bot'
description: 'The bot automating the enovitae organization publications'
author: 'enovitae'

branding:
  icon: 'activity'
  color: 'red'

inputs:
  github_token:
    description: 'GITHUB_TOKEN'
    required: false
    default: '${{ github.token }}'
  username:
    description: The username of the bot
    required: false
    default: bot

runs:
  using: node20
  main: dist/index.js
